name: Publish

on:
  push:
    branches: [ master ]
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Publish win-x64
      run: dotnet publish -p:PublishProfile=win-x64.pubxml Obj2Tiles
    - name: Publish win-arm
      run: dotnet publish -p:PublishProfile=win-arm.pubxml Obj2Tiles
    - name: Publish win-arm64
      run: dotnet publish -p:PublishProfile=win-arm64.pubxml Obj2Tiles
    - name: Publish linux-x64
      run: dotnet publish -p:PublishProfile=linux-x64.pubxml Obj2Tiles
    - name: Publish linux-arm
      run: dotnet publish -p:PublishProfile=linux-arm.pubxml Obj2Tiles
    - name: Publish osx-x64
      run: dotnet publish -p:PublishProfile=osx-x64.pubxml Obj2Tiles  
    
    - uses: actions/upload-artifact@v3
      with:
        name: Build win-x64
        path: ./Obj2Tiles/bin/Release/net6.0/publish/win-x64/   
        
    - uses: actions/upload-artifact@v3
      with:
        name: Build win-arm
        path: ./Obj2Tiles/bin/Release/net6.0/publish/win-arm/
        
    - uses: actions/upload-artifact@v3
      with:
        name: Build win-arm64
        path: ./Obj2Tiles/bin/Release/net6.0/publish/win-arm64/
        
    - uses: actions/upload-artifact@v3
      with:
        name: Build linux-x64
        path: ./Obj2Tiles/bin/Release/net6.0/publish/linux-x64/
        
    - uses: actions/upload-artifact@v3
      with:
        name: Build linux-arm
        path: ./Obj2Tiles/bin/Release/net6.0/publish/linux-arm/
      
    - uses: actions/upload-artifact@v3
      with:
        name: Build osx-x64
        path: ./Obj2Tiles/bin/Release/net6.0/publish/osx-x64/
